Ranz/update from origin
untetherai/onnx2torch2 pull request #13
Opened 2024-08-16 02:00 UTC by ranz-UAI

This PR update our untetherai onnx2torch2 with changes from original onnx2torch branch

2024-08-19 13:25 UTC, ofershai approved these changes, later dismissed

2024-08-19 14:26 UTC, goelbenj requested changes

2024-08-19 14:26 UTC, goelbenj commented on .pre-commit-config.yaml
We are no longer using the `.pylintrc` file to configure the linting

2024-08-20 15:04 UTC, ranz-UAI commented on .pre-commit-config.yaml
@goelbenj should we delete the `lint.yml` file?

2024-08-21 03:01 UTC, goelbenj approved these changes

2024-08-21 18:25 UTC, merged